# =========================== Basic Settings ===========================
# machine info
num_gpus_per_job: 1  # number of gpus each job need
num_cpus_per_job: 4  # number of gpus each job need
num_hosts_per_job: 1
memory_per_job: 1  # number of gpus each job need
gpu_type: 'nvidia-mx-150'

# parameters
name: model_dir 
model_restore: 'logs/model_dir'  # logs/places2_gated_conv
dataset: 'sat' 
random_crop: False  # Set to false , meaning only resize the images to img_shapes, instead of crop img_shapes from a larger raw image. This is useful when you train on images with different resolutions.
val: True  # true if you want to view validation results in tensorboard
log_dir: logs/model_dir

gan: 'sngan'
gan_loss_alpha: 1
gan_with_mask: True
discounted_mask: True
random_seed: False
padding: 'SAME'

# training
train_spe: 1000
max_iters: 100000000
viz_max_out: 10
val_psteps: 2000

# data
data_flist:
  sat: [
    'data_flist/train_shuffled.flist',
    'data_flist/validation_shuffled.flist'
  ]

static_view_size: 0
img_shapes: [256, 256, 3]
height: 128
width: 128
max_delta_height: 32
max_delta_width: 32
batch_size: 1
vertical_margin: 0
horizontal_margin: 0

# loss
ae_loss: True
l1_loss: True
l1_loss_alpha: 1.

